In [2]:
import numpy as np

In [3]:
# 构造矩阵
p = np.mat('8 7 6 8;7 8 8 7') #每一行代表一个对象的指标评分
print(p)
#A为自己构造的输入判别矩阵
A = np.array([[1,3,1,1/3],[1/3,1,1/2,1/5],[1,2,1,1/3],[3,5,3,1]])
print(A)

[[8 7 6 8]
 [7 8 8 7]]
[[1.         3.         1.         0.33333333]
 [0.33333333 1.         0.5        0.2       ]
 [1.         2.         1.         0.33333333]
 [3.         5.         3.         1.        ]]


In [4]:
#查看行数和列数
[m,n] = A.shape
print(m,n)

4 4


In [5]:
#求特征值和特征向量
V,D = np.linalg.eig(A)
print('特征值：')
print(V)
print('特征向量：')
print(D)

特征值：
[ 4.03413707e+00+0.j        -1.70685331e-02+0.3707051j
 -1.70685331e-02-0.3707051j  3.96956267e-17+0.j       ]
特征向量：
[[-3.40590354e-01+0.j         -3.03369854e-01+0.31051952j
  -3.03369854e-01-0.31051952j  1.73785334e-01+0.j        ]
 [-1.45447924e-01+0.j         -7.87517900e-02-0.16863676j
  -7.87517900e-02+0.16863676j -7.77409098e-17+0.j        ]
 [-3.04536070e-01+0.j          1.40815220e-01+0.07762988j
   1.40815220e-01-0.07762988j -4.63427557e-01+0.j        ]
 [-8.77553926e-01+0.j          8.66630736e-01+0.j
   8.66630736e-01-0.j          8.68926670e-01+0.j        ]]


In [6]:
#最大特征值
tzz = np.max(V)
print(tzz)
#最大特征向量
k=[i for i in range(len(V)) if V[i] == np.max(V)]
tzx = -D[:,k]
print(tzx)

(4.034137066247205+0j)
[[0.34059035-0.j]
 [0.14544792-0.j]
 [0.30453607-0.j]
 [0.87755393-0.j]]


In [7]:
# #赋权重
quan=np.zeros((n,1))
for i in range(0,n):
    quan[i]=tzx[i]/np.sum(tzx)
Q=quan
print(Q)

[[0.20417516]
 [0.08719229]
 [0.18256154]
 [0.52607101]]


C:\Users\Monty _L\AppData\Local\Temp\ipykernel_19788\2855422392.py:4: ComplexWarning: Casting complex values to real discards the imaginary part
  quan[i]=tzx[i]/np.sum(tzx)


In [8]:
#一致性检验
CI=(tzz-n)/(n-1)
RI=[0,0,0.58,0.9,1.12,1.24,1.32,1.41,1.45,1.49,1.52,1.54,1.56,1.58,1.59]
#判断是否通过一致性检验
CR=CI/RI[n-1]
if CR>=0.1:
    print('没有通过一致性检验\n')
else:
    print('通过一致性检验\n')

通过一致性检验



In [9]:
#显示出所有评分对象的评分值
score=p*Q
for i in range(len(score)):
    print('object_score {}：'.format(i),float(score[i]))

object_score 0： 7.547684625992974
object_score 1： 7.269753832009365
